### ISSUE TITLE
iOS Accelerometer StartReading silent crash (Potential bug)

### ISSUE THREAD

**Issue by FilledStacks** [CrossGeeks/DeviceSensorsPlugin#1]
Hey,

I've been using this plugin in my Xamarin app and it works fine on Android. I was having problems with iOS where the StartListening call would just crash silently. I couldn't get your project to restore properly in my solution so I just took your code and added it in to test what the problem was.

I am calling the StartReading function on the Accelerometer from a System.Timers.Timer.Elapsed callback, meaning there's no NSOperationQueue.CurrentQueue since [this value only reflects the operation queue that launched the opration](https://developer.apple.com/documentation/foundation/nsoperationqueue/1413097-currentqueue). This causes a silent crash and doesn't provide any feedback from your plugin.

I would make the change and make a PR, but as mentioned above the project is not restoring in my solution (which contains .netstandard2 libs) and I don't want to submit PR not tested by me.

I fixed the problem by just using NSOperation.MainQueue instead of CurrentQueue and the reading works again, just as a workaround for now.

Suggestions:

- Use NSOperation.MainQueue in Platforms/iOS/AccelerometerDeviceSensor.cs line 51
- **Additionally:** Use the NSError returned (if any) to throw an exception in OnAccelerometerChanged
- **Additionally:** Surround _motionManager.StartAccelerometerUpdates(NSOperationQueue.CurrentQueue, OnAccelerometerChanged); in a try catch and throw a custom exception to indicate "Not called from the UIThread" or something in those regards or you can make sure the call is being performed on the UI thread to ensure that NSOperationQueue.CurrentQueue is not null.

If I missed anything and it's my code causing the issue you can just close this.

I hope this helps

**Comment by rdelrosario** [comment]
Thanks for this finding will fix on next version!

**Comment by rdelrosario** [comment]
Should be fixed on version:

https://www.nuget.org/packages/Plugin.DeviceSensors/1.0.0
